### ISSUE TITLE
Allow or deny vanilla command overrides

### ISSUE THREAD

**Issue by SheerYin** [WiIIiam278/HuskHomes2#164] opened 2022-04-01 12:22 UTC
Similar to cmi's commands, cmi will allow or deny vanilla commands to be overridden in aliased commands.
If you refuse to overwrite the vanilla command "/cmi tp"

**Comment by WiIIiam278** [comment] 2022-04-01 13:33
Duplicate of #154

**Closed by WiIIiam278** 2022-04-01 13:33 UTC
