### ISSUE TITLE
Option to, force teleport player upondeath to the bungee network spawn

### ISSUE THREAD

**Issue by Tizinais** [WiIIiam278/HuskHomes2#182] opened 2022-06-17 16:17 UTC
When you die anywhere on the network. (With this option enabled)
You would be send to the network spawn instead of the world spawn.

**Comment by WiIIiam278** [comment] 2022-07-06 11:38
Respawn handling isn't a feature of HuskHomes at the moment. Marking as duplicate of https://github.com/WiIIiam278/HuskHomes2/issues/123

**Closed by WiIIiam278** 2022-07-06 11:38 UTC
