### ISSUE TITLE
Problems that still appear in the latest version

### ISSUE THREAD

**Issue by DCE-114514** [WiIIiam278/HuskHomes2#417] opened 2023-05-28 11:01 UTC
Hello, I have used the latest version of huskhomes, and this problem will still occur. The environment is waterfall, with five sub-servers. The version used by MySQL is 8.0, and there is no error in the background. The version and problems are in the picture, and the language is simplified Chinese.![81290fdb01044dc6.jpg](https://github.com/WiIIiam278/HuskHomes2/assets/132117183/0a2e4b8e-711a-4103-9fbc-c9bf647efb79)

![-95fed3ab33815fb.jpg](https://github.com/WiIIiam278/HuskHomes2/assets/132117183/35f40daa-bb66-4925-a01a-beda628fe23f)

![Screenshot_2023-05-28-17-25-35-133_com.microsoft.rdc.androidx.png](https://github.com/WiIIiam278/HuskHomes2/assets/132117183/ca07e48e-31ce-439d-b913-595e4b96108b)

**Comment by WiIIiam278** [comment] 2023-05-28 13:12
Duplicate of #415.
Please don't open duplicate issues :)

**Closed by WiIIiam278** 2023-05-28 13:12 UTC

**Comment by DCE-114514** [comment] 2023-05-28 13:14
> Duplicate of #415.
> Please don't open duplicate issues :)

ok sorry( I don't use github very often.
