### ISSUE TITLE
Tasks still fail to cancel correctly in 4.3.3

### ISSUE THREAD

**Issue by DCE-114514** [WiIIiam278/HuskHomes2#415] opened 2023-05-27 04:01 UTC
The server is a group server. After updating to the latest plug-in, sometimes the player will appear in a certain area as shown in the figure, and can only transmit after changing the area. I hope the author can fix it, thank you.![-7272e7602e2e951d.jpg](https://github.com/WiIIiam278/HuskHomes2/assets/132117183/e7642662-2d81-4f65-8a94-380df84d7f59)

**Comment by WiIIiam278** [comment] 2023-05-27 09:53
I'm not able to ascertain what error you're experiencing.
Could  you please try downloading the latest build here: https://modrinth.com/plugin/huskhomes/version/4.3.3-b5100fa

**Comment by DCE-114514** [comment] 2023-05-27 09:54
ok please wait

**Comment by DCE-114514** [comment] 2023-05-27 09:54
> I'm not able to ascertain what error you're experiencing, but it looks familiar.
> Could you please try downloading the latest build here: https://modrinth.com/plugin/huskhomes/version/4.3.3-b5100fa and reproducing?

ok please wait

**Comment by DCE-114514** [comment] 2023-05-27 09:56
> I'm not able to ascertain what error you're experiencing, but it looks familiar.
> Could you please try downloading the latest build here: https://modrinth.com/plugin/huskhomes/version/4.3.3-b5100fa and reproducing?
Ok, I'll try the latest edition, thank you.

**Comment by DCE-114514** [comment] 2023-05-27 09:56
> I'm not able to ascertain what error you're experiencing, but it looks familiar.
> Could you please try downloading the latest build here: https://modrinth.com/plugin/huskhomes/version/4.3.3-b5100fa and reproducing?

Ok, I'll try the latest edition. Thank you.

**Comment by DCE-114514** [comment] 2023-05-28 09:26
> I'm not able to ascertain what error you're experiencing, but it looks familiar.
> Could you please try downloading the latest build here: https://modrinth.com/plugin/huskhomes/version/4.3.3-b5100fa and reproducing?

hello
the error as before![Screenshot_2023-05-28-17-25-35-133_com.microsoft.rdc.androidx.png](https://github.com/WiIIiam278/HuskHomes2/assets/132117183/0009c245-fd67-492d-b6f6-ba2395fcf35e)

**Comment by iVillager** [comment] 2023-05-31 08:57
Any news on this issue? I'm having problems too

**Comment by DCE-114514** [comment] 2023-05-31 08:58
Wait for the plug-in update

**Comment by WiIIiam278** [comment] 2023-06-02 19:17
Should be fixed with https://modrinth.com/plugin/huskhomes/version/4.3.3-e17af77.
Please try and reproduce.

**Comment by WiIIiam278** [comment] 2023-06-03 11:59
Closing as this seems to be resolved -- cannot reproduce. If it's not, well, I'm really confused.

**Closed** 2023-06-16 11:19 UTC
Labels: type: bug, status: needs testing
