### ISSUE TITLE
Add PlayerTeleportRequestEvent?

### ISSUE THREAD

**Issue by twseer67875** [WiIIiam278/HuskHomes2#227] opened 2022-09-20 08:39 UTC
Is it possible to add things like PlayerTeleportRequestEvent and PlayerBackEvent ?

Since there doesn't seem to be a way for the API to know the events that send /tpa /tpahere and /back, since I currently want to do something before the player sends the teleport request and the player returns, can we add the above two events for us to listen?

**Comment by WiIIiam278** [comment] 2022-09-20 10:27
Partially duplicate of #180
But yeah I agree a teleport request event would be good. I'll probably add more teleport types so you could listen to the teleport event and check the type/cause as "BACK" or something

**Comment by twseer67875** [comment] 2022-09-20 10:52
@WiIIiam278 Is there a specific time to add because it was needed recently, or maybe this content will take longer to add?

**Comment by WiIIiam278** [comment] 2022-09-20 10:52
> @WiIIiam278 Is there a specific time to add because it was needed recently, or maybe this content will take longer to add?

I don't do timeframes :)

**Closed** 2023-04-03 11:27 UTC
Labels: type: feature request
