### ISSUE TITLE
Add more economy hook actions for basic commands

### ISSUE THREAD

**Issue by AyolK0327** [WiIIiam278/HuskHomes2#295] opened 2023-01-02 15:43 UTC
Like RANDOM_TELEPORT and BACK_COMMAND, When the user executes the command, it will cost some money.
Make these commands have actions for Economy Hook：
/home,/warp,/tpa,/tp,/spawn,/tpahere
maby more

Sorry, my English is terrible

**Comment by WiIIiam278** [comment] 2023-03-24 01:38
Duplicate of #127

**Closed by WiIIiam278** 2023-03-24 01:38 UTC
Labels: resolution: invalid
