### ISSUE TITLE
Bugs after updating the new version

### ISSUE THREAD

**Issue by DCE-114514** [WiIIiam278/HuskHomes2#411] opened 2023-05-21 22:05 UTC
After using tpa or back, the probability of players repeatedly prompting "successful transmission" is very small, but once it appears, the server must be restarted to solve it. I hope the author can fix it. I use waterfall and the language is zh_cn.![Screenshot_2023-05-22-06-03-03-810_com.tencent.mobileqq.jpg](https://github.com/WiIIiam278/HuskHomes2/assets/132117183/f4e43502-88aa-4c7b-8fed-ae60a7554e65)

The server is online for 40-60 people every day, and 11 days after the plug-in is updated, a total of five people have this situation.

**Comment by WiIIiam278** [comment] 2023-05-21 22:58
Duplicate of #405

**Closed by WiIIiam278** 2023-05-21 22:58 UTC
