### ISSUE TITLE
Commands stop working after an erorr

### ISSUE THREAD

**Issue by Vally90** [WiIIiam278/HuskHomes2#302] opened 2023-01-17 23:03 UTC
After this error Huskhomes stop to work, so the players cant run command like /home,/spawn ecc

```
[22:23:10] [Server thread/INFO]: Ninja388 issued server command: /tpa ky
[22:23:13] [Server thread/INFO]: Ninja388 issued server command: /tpa kyuimo
[22:23:13] [Server thread/INFO]: ZombieLara89 issued server command: /home diam
[22:23:16] [CompletableFutureDelayScheduler/WARN]: [HuskHomes] Message dispatch after 5 seconds
java.util.concurrent.TimeoutException: null
    at java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2874) ~[?:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:23:18] [CompletableFutureDelayScheduler/WARN]: [HuskHomes] Message dispatch after 5 seconds
java.util.concurrent.TimeoutException: null
    at java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2874) ~[?:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:23:21] [Server thread/INFO]: Ninja388 issued server command: /r lag
```

**Comment by WiIIiam278** [comment] 2023-01-18 00:14
duplicate of #275

**Closed by WiIIiam278** 2023-01-18 00:14 UTC
