### ISSUE TITLE
Add support for different Messages on TPA-Requests for Bedrock Players

### ISSUE THREAD

**Issue by Ekmot276** [WiIIiam278/HuskHomes2#106] opened 2021-11-18 08:29 UTC
Allow users to specify different Teleport-Request-Messages depending on if the targeted player is a bedrock or java players.

The user reported, that bedrock-players might not be able to click on chat messages and accept or deny messages by that way, but he does not want to lose the functionality for java-players.

Effected commands:
- /tpa
- /tpahere

Might need some work to hook into Geyser or something to specify what version of minecraft they are using (java/bedrock).

**Comment by kerostampcrab** [comment] 2021-11-18 11:06
You can hook up Floodgate API, should be easy and let's you identify the player is on Bedrock. Most people use Floodgate with Geyser.

**Comment by WiIIiam278** [comment] 2021-11-21 02:22
Not impossible to implement (possibly through checking if username contains the bedrock gamertag disambiguator) but the issue is HuskHomes is a Spigot plugin, so it's not possible to hook into the floodgate API which I understand is a proxy plugin.
Fundamentally, though, I'm not sure if it's a good idea to design Spigot plugins for Bukkit users necessarily. I agree making it _accessible_ to those clients (which HH already is), but feel like that's more of an issue that needs to be addressed in MC:BE parity updates and Geyser improvements.
I think I am going to shelve this request for now until either a better solution crops up

**Comment by kerostampcrab** [comment] 2021-11-21 06:06
Ahhaha, I told you "Most people use the Floodgate plugin with Geyser" which probably means Floodgate is a plugin. So is Geyser a plugin (there's also a server jar for it, but there's a spigot plugin which is the only thing people use). This wouldn't be any different than other APIs like Pl3xmap.

**Comment by kerostampcrab** [comment] 2021-11-21 06:23
Oh, I see you understanded it's a plugin but, I think it should be easy.

**Comment by WiIIiam278** [comment] 2021-11-21 10:02
> Oh, I see you understanded it's a plugin but, I think it should be easy. Yes, many Spigot plugins use the Floodgate API.

It's my understanding that you install Floodgate on the proxy, though? Not on the spigot servers

**Comment by kerostampcrab** [comment] 2021-11-21 11:08
> > Oh, I see you understanded it's a plugin but, I think it should be easy. Yes, many Spigot plugins use the Floodgate API.
> 
> It's my understanding that you install Floodgate on the proxy, though? Not on the spigot servers

No no no, this is how it works. You have a Spigot server, and you download the Geyser plugin. It works like that, but for connections without the need for the Bedrock players to need a Java account, you would download Floodgate. Floodgate gives you hybrid mode connections, so Bedrock players do not need a Java account.

There is no other thing for a proxy, all of this can be run on a single server.

**Comment by WiIIiam278** [comment] 2021-11-21 12:33
> > > Oh, I see you understanded it's a plugin but, I think it should be easy. Yes, many Spigot plugins use the Floodgate API.
> > 
> > 
> > It's my understanding that you install Floodgate on the proxy, though? Not on the spigot servers
> 
> No no no, this is how it works. You have a Spigot server, and you download the Geyser plugin. It works like that, but for connections without the need for the Bedrock players to need a Java account, you would download Floodgate. Floodgate gives you hybrid mode connections, so Bedrock players do not need a Java account. Floodgate is like an addon for Geyser. They are just Spigot plugins.
> 
> There is no other thing for a proxy, all of this can be run on a single server.

According to the Geyser wiki:
[If you are using a BungeeCord, Waterfall, or Velocity proxy, then you only need to install Geyser (and Floodgate, if you desire) on the proxy.
](https://github.com/GeyserMC/Geyser/wiki/Setup#bungeecordvelocity-setup)

I'd wager the vast majority of Geyser users are running the setup in this way. 
With that said, the API you linked does say that with some configuration (and what I assume is also requiring users to install the floodgate plugin on the spigot servers) [it is possible](https://github.com/GeyserMC/Floodgate/wiki/FloodgateApi#using-the-api-on-backend-servers) to make it work even with this setup, though it's a bit unclear

**Comment by kerostampcrab** [comment] 2021-11-21 12:41
Completely forgot about Bungeecord. :sweat_smile:

**Comment by fabegalo** [comment] 2022-01-05 05:11
Hi, I came here to ask a question, when bedrock players create public homes, the command to teleport to those players' homes contains the floodgate prefix, for example /phome *PlayerName.home

, the problem when it contains * in the command it says that the syntax is incorrect, is there any way to get around it?

**Comment by WiIIiam278** [comment] 2022-01-29 01:18
> Hi, I came here to ask a question, when bedrock players create public homes, the command to teleport to those players' homes contains the floodgate prefix, for example /phome *PlayerName.home, the problem when it contains * in the command it says that the syntax is incorrect, is there any way to get around it?
> 
> ![image](https://user-images.githubusercontent.com/53371411/148163997-674c3b86-8f40-4884-8c31-a873b2522729.png)
> 
> @WiIIiam278

Sorry for the late reply, this isn't really related to this issue at hand though is an oversight with regard to the regex being done on that not accounting for bedrock accounts. More config options are needed here probably

**Comment by WiIIiam278** [comment] 2022-09-09 22:22
Decided to close this issue as I don't really think it's in scope for the plugin to try and detect and account for Bedrock players when sending messages and would probably lead to excessive locale bloat for what is ultimately an edge-case.

**Closed by WiIIiam278** 2022-09-09 22:22 UTC
Labels: type: feature request, status: postponed
