### ISSUE TITLE
"playerID" is null

### ISSUE THREAD

**Issue by Suhkur** [WiIIiam278/HuskHomes2#181] opened 2022-05-27 14:03 UTC
Hello, my console seems to be spammed by huskhomes.

[16:54:55 WARN]: [HuskHomes] Plugin HuskHomes v2.11.2 generated an exception while executing task 3135
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "playerID" is null
        at me.william278.huskhomes2.data.DataManager.getPlayerInteger(DataManager.java:57) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.getPlayerInteger(DataManager.java:71) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.deletePlayerLastPosition(DataManager.java:757) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.data.DataManager.setPlayerLastPosition(DataManager.java:705) ~[HuskHomes-2.11.2.jar:?]
        at me.william278.huskhomes2.listeners.PlayerListener.lambda$onPlayerDie$0(PlayerListener.java:34) ~[HuskHomes-2.11.2.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>

Im using purpur 1628, huskhomes 2.11.2

**Comment by Suhkur** [comment] 2022-06-02 16:50
> Is your server cracked?

Hello!

The issue suddenly has seemed to resolve itself, i tried both offline mode and online mode and had the same issue
but suddenly it no longer spammed the console anymore in online or offline mode.

So in conclusion, no idea what fixed it i was initially using offline mode when the errors started happening then switched to online(errors were still appearing, then stopped randomly).

**Comment by WiIIiam278** [comment] 2022-06-02 19:30
Interesting, weird, etc - I'm guessing it was the offline mode thing. Closing this as unable to reproduce.

**Closed by WiIIiam278** 2022-06-02 19:30 UTC
Labels: type: question
