### ISSUE TITLE
The sound cannot be modified

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#226] opened 2022-09-20 03:05 UTC
After modifying the sound in `general.sound_effects`, restarting or reloading the plugin will restore the default value. 

I tried modifying the sound to `block.note_block.harp`.

**Comment by WiIIiam278** [comment] 2022-09-20 10:24
Duplicate of #220 - already fixed in latest dev build

**Closed** 2022-09-20 10:24 UTC
