### ISSUE TITLE
Global re-spawning: Allow re-spawning to global spawn rather than local spawn if bed not defined

### ISSUE THREAD

**Issue by Ceddix** [WiIIiam278/HuskHomes2#223] opened 2022-09-19 13:34 UTC
Currently, if a player does not have a global respawn point, he respawns at the respawn point of his current server _(which is either a bed or the spawn of this server)_.
Therefore, I thought it would be nice if you could, for example, select that you respawn at the global spawn in this case.

**Comment by WiIIiam278** [comment] 2023-03-24 01:35
Duplicate of #279

**Closed by WiIIiam278** 2023-03-24 01:35 UTC
Labels: type: feature request
