### ISSUE TITLE
Players with similar nicks tpa bug

### ISSUE THREAD

**Issue by thiagogebrimm** [WiIIiam278/HuskHomes2#313] opened 2023-02-15 02:48 UTC
If my nickname is "thiagogebrim" and there is another player online with the nickname "thiago" and I send tpa to someone, if they accept the player "thiago" who is teleported

**Comment by WiIIiam278** [comment] 2023-02-16 12:56
Duplicate of #288

**Closed** 2023-02-16 12:56 UTC
