### ISSUE TITLE
Players cannot transmit while moving

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#260] opened 2022-11-16 13:05 UTC
repro steps: 

1. player_A always moving
2. player_A: `/tpa player_B`
3. player_B: assent to a request
4. player_A not transmitted

I tried to change the transmission waiting time in the configuration to 0, which has no effect.

**Comment by WiIIiam278** [comment] 2022-11-22 14:16
Duplicate of #258

**Closed by WiIIiam278** 2022-11-22 14:16 UTC
Labels: type: bug
