### ISSUE TITLE
Add option to charge per use of the /tpa command

### ISSUE THREAD

**Issue by TechRoot** [WiIIiam278/HuskHomes2#167] opened 2022-04-16 22:54 UTC
As a suggestion:

Add TPA into Economy builtin system, so we can setup a fee for TPA usage.
Also, permission nodes to avoid this cost would be implemented.

**Comment by WiIIiam278** [comment] 2022-05-20 19:42
This is already a feature:
```
economy_integration:
  enabled: false
  free_home_slots: 5
  costs:
    additional_home_slot: 100
    make_home_public: 50
    random_teleport: 20
    back: 0
    ```

**Comment by WiIIiam278** [comment] 2022-05-20 19:43
Nvm, I misread.

**Comment by WiIIiam278** [comment] 2022-08-22 23:52
Duplicate of #127

**Closed by WiIIiam278** 2022-08-22 23:52 UTC
Labels: type: feature request
