### ISSUE TITLE
function request - Feature request /dellallhome example world

### ISSUE THREAD

**Issue by DeEthria** [WiIIiam278/HuskHomes2#321] opened 2023-03-16 00:41 UTC
Good day.
As already requested in Discord, a function for admins to delete all homes in a specific world would be great. Some servers, like us, operate a city build network where all worlds are reset with a new "Minecraft Seed" once a month. Say every first of the month we regenerate our worlds "Nether, End, Oberwelt". After regenerating, it sucks if a player types /home xyz and spawns in lava or rock.

A function for admins or a command /delallhomes World_The_End or The_Nether etc. would be cool.

Sorry if I'm in the wrong section, I'm not very familiar with github

**Comment by WiIIiam278** [comment] 2023-05-04 11:04
Duplicate of #257

**Closed by WiIIiam278** 2023-05-04 11:04 UTC
Labels: type: feature request
