### ISSUE TITLE
TPA request bug

### ISSUE THREAD

**Issue by jamexhuang** [WiIIiam278/HuskHomes2#68] opened 2021-07-12 19:36 UTC
Sending a /tpa request to random ID, but didn't receive "error_player_not_found ".
![image](https://user-images.githubusercontent.com/16366999/125345519-368b7300-e38b-11eb-943b-95bd09371fec.png)

**Comment by jamexhuang** [comment] 2021-07-12 19:39
I think maybe the tpa request should be only sent to online players?

**Comment by Iotados** [comment] 2021-07-12 19:44
I am unable to replicate this issue using latest version 2.6.3. Can you please say what version your using?

**Comment by WiIIiam278** [comment] 2021-07-12 19:44
Hey, currently HuskHomes does not restrict who you can attempt to teleport
to when bungee mode is enabled as it doesn't track all players on your
bungee network for every teleport (mainly for performance reasons
currently) - so that player could be online on another server for instance.
What *could* be done is some basic checks to ensure the player is actually
valid - in the future these checks could be made to ensure that the target
is legitimate - but I'd rather avoid having to query each server with a
plugin message whenever someone uses a teleport command. I could look into
improving the TAB completion cache for this purpose in the future.
Closing this as Works as Intended for now - but might revisit later.

**Closed by WiIIiam278** 2021-07-12 19:44 UTC
Labels: status: needs testing
