### ISSUE TITLE
Teleportation hangs on fabric due to sounds not playing correctly

### ISSUE THREAD

**Issue by 1264175987** [WiIIiam278/HuskHomes2#434] opened 2023-06-11 15:34 UTC
Players cannot teleport after type teleport command , when they type /tpa xxx or any other teleport command of huskhome , they will be told "You will be teleported in 5 seconds , please stand" and then nothing happen . 
If they type any teleport command of huskhomes after this , they will be told "You must wait for the last teleport finish", and there is nothing wrong in the server console , players can only teleport after obtaining administrator permission.
The server is fabric-server-mc.1.20-loader.0.14.21-launcher.0.11.2
Server mods include
fabric-api-0.83.0+1.20
HuskHomes-Fabric-4.3.3-d4b37e3

By the way , this mod can not generate "server.yml" automatic ，I did this by my self.

And this is my config
https://pastebin.com/RDN06R0v

**Comment by WiIIiam278** [comment] 2023-06-11 16:24
HuskHomes on Fabric 1.20 is not ready yet; this is an upstream issue caused by `adventure-platform-fabric` not supporting 1.20 yet.

**Comment by WiIIiam278** [comment] 2023-06-16 11:20
sounds disabled for initial 1.20.1 release, closed in #433

**Closed by WiIIiam278** 2023-06-16 11:20 UTC
Labels: type: bug, platform: fabric
