### ISSUE TITLE
Imported public homes & warps won't appear on map hooks due to UUID zeroing on import

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#215] opened 2022-09-12 14:28 UTC
I have map integration enabled, but there are no teleports in the map.  
This is the config for map integration: 
```
map_hook:
  enabled: true
  map_plugin: DYNMAP
  show_public_homes: false
  show_warps: true
```

Edit: 
Dynmap: `3.4-beta-5`.  
HuskHomes: `v3.0.2`.  
(HuskHomes 2.x does not have this problem)  

This is the json in the dynmap database: (This map has over 47 warps.)
![image](https://user-images.githubusercontent.com/59365724/189688346-00ed068f-5711-4791-867d-ef81c78d18ed.png)

Do I need to provide other information?

**Comment by WiIIiam278** [comment] 2022-09-12 15:04
I did test against that version of dynmap and it worked for me. Are you sure it's just not because there's no warps on your server?

**Comment by ApliNi** [comment] 2022-09-12 15:08
There are many warps in the server, but they are all updated from the 2.x version.
I just tried to create a warp in version 3.x, it can be displayed normally.

**Comment by ApliNi** [comment] 2022-09-12 15:08
There are many warps in the server, but they are all updated from the 2.x version.
I just tried to create a warp in version 3.x, it can be displayed normally.

**Comment by WiIIiam278** [comment] 2022-09-12 17:20
Could you clarify - it works adding new warps but existing warps don't appear on the server start?

**Comment by ApliNi** [comment] 2022-09-12 17:23
Yes, existing warps will not appear on the dynmap.
I am sure that the data migration is successful, and the warp can be used normally.

**Comment by WiIIiam278** [comment] 2022-09-12 17:24
Try a server restart - after the restart, how many warps appear? None? Or only newly set warps?

**Comment by ApliNi** [comment] 2022-09-12 17:25
No warp appears on dynmap after restart.
Only newly added warps will be displayed.

**Comment by WiIIiam278** [comment] 2022-09-12 17:42
OK— thanks, will have to test and take a look

**Comment by WiIIiam278** [comment] 2022-09-15 14:13
![2022-09-15_15 11 47](https://user-images.githubusercontent.com/31187453/190426200-544c90ab-808c-43d3-b9f9-6114cdfd8d53.png)
Just tested with Dynmap v3.4-828 and am _unable to reproduce_.

I did push two small changes to the way server names are fetched // RTP caching, but my understanding is this is unrelated to cross-server setups (and don't see how this could affect it)

Please try updating to this build of dynmap (latest downloaded from spigotmc.org) and try again. Happy to reopen if a method of reliably reproducing this can be found.

**Comment by ApliNi** [comment] 2022-09-15 14:43
I re-tested and recorded the whole process. 
All settings not mentioned except dynmap use default values. 
(I can't open issues that have been closed as unscheduled. )


1. Install Minecraft Server 1.19.2
2. Install Dynmap-3.4-spigot
3. Install HuskHomes-2.11.2, set `map_integration.enabled: true`
4. Start the server
5. Enter the game, type `/setwarp warp1`
6. Open the Dynmap web page and view warp1 (warp can be displayed normally at this time).
7. Shut down the server
8. Delete HuskHomes-2.11.2, install HuskHomes-3.0.2
9. Delete HuskHomes/config.yml
10. Start the server, then shut down the server
11. Modify the configuration `map_hook.enabled: true`
12. Start the server
13. Open the Dynmap webpage and view warp1 (no warp can be seen at this time)
14. Enter the game, type `/setwarp warp2`
15. Open the Dynmap webpage and view warp2 (warp2 is displayed normally at this time)
16. Restart the server
17. Open the Dynmap webpage and view the warp (warp2 is displayed normally at this time, but warp1 is not displayed)


6. warp1 normal display
![image](https://user-images.githubusercontent.com/59365724/190430661-ae6fdb93-dec0-4d74-afb0-cdc58c1fb5d2.png)


13. warp1 Do not show
![image](https://user-images.githubusercontent.com/59365724/190432465-c26f1fc3-084f-4b8b-bee7-a1f7036ce662.png)


17. warp1 Do not show, warp2 normal display
![image](https://user-images.githubusercontent.com/59365724/190432448-b8005cb9-2887-4a1f-bec8-b4b891ac73b5.png)


---

```
1. 安装1.19.2的Minecraft服务器
2. 安装Dynmap-3.4-spigot
3. 安装HuskHomes-2.11.2, 设置`map_integration.enabled: true`
4. 启动服务器
5. 进入游戏, 输入`/setwarp warp1`
6. 打开Dynmap网页, 查看 warp1 (此时warp可以正常显示). 
7. 关闭服务器
8. 删除HuskHomes-2.11.2, 安装HuskHomes-3.0.2
9. 删除HuskHomes/config.yml
10. 启动服务器, 然后关闭服务器
11. 修改配置`map_hook.enabled: true`
12. 启动服务器
13. 打开Dynmap网页, 查看 warp1 (此时看不见任何warp)
14. 进入游戏, 输入`/setwarp warp2`
15. 打开Dynmap网页, 查看 warp2 (此时warp2正常显示)
16. 重启服务器
17. 打开Dynmap网页, 查看 warp (此时warp2正常显示, warp1不显示)
```

**Comment by WiIIiam278** [comment] 2022-09-15 14:56
I think this might be caused by the fact that HuskHomes v3 has a new icon scheme / marker sets and the cached json that Dynmap stores aren't getting deleted during the migration process.
Could you try with a fresh install of dynmap (delete /dynmap/ folder in /plugins/) _after_ upgrading from HuskHomes v2.11.2?

**Comment by WiIIiam278** [comment] 2022-09-15 15:05
Actually, nevermind. I know why this is happening. It's caused by the fact that HuskHomes v3 uses the world UUIDs of public homes and warps to identify where they should be set on startup, because the server ID cannot be guaranteed. However, HuskHomes v2 doesn't save world UUIDs at all, so upon import those IDs are zeroed out. Thus, existing homes won't display on the map.
This can be fixed by updating the map integration to use the server and world name as a way of checking in addition and making the world UUIDs be used on backup.

**Comment by ApliNi** [comment] 2022-09-15 15:06
I tried in my test server, delete all files except dynmap/configuration.txt.
warp not recovered

**Comment by WiIIiam278** [comment] 2022-09-15 15:16
@ApliNi No, it's an issue with my implementation. I'm about to push a fix.

**Comment by ApliNi** [comment] 2022-09-15 15:17
ok, thanks, if possible I hope it fixes the data already in the 3.x version.

**Comment by WiIIiam278** [comment] 2022-09-15 15:18
> ok, thanks, if possible I hope it fixes the data already in the 3.x version.

Please try with https://modrinth.com/plugin/huskhomes/version/3.0.3-a9e643d

**Comment by ApliNi** [comment] 2022-09-15 15:24
> Please try with https://modrinth.com/plugin/huskhomes/version/3.0.3-a9e643d

It doesn't seem to work:
I tried using it to replace the 3.x version and it didn't fix the uuid of 00000.
Try to use it to migrate 2.x version data, still the uuid of 00000.

**Comment by WiIIiam278** [comment] 2022-09-15 15:26
> > Please try with https://modrinth.com/plugin/huskhomes/version/3.0.3-a9e643d
> 
> It doesn't seem to work: I tried using it to replace the 3.x version and it didn't fix the uuid of 00000. Try to use it to migrate 2.x version data, still the uuid of 00000.
> 
> Edit: `HuskHomes-Plugin-3.0.3-a9e643d.jar`

This version _will not_ correct the UUIDs - those are set to 0 on purpose. What it should do is let them display on the map -- that's the nature of this issue, not the UUID zeroing (intended, as HH2 does not store that data -- and there are issues with trying to interpolate that)

**Comment by ApliNi** [comment] 2022-09-15 15:28
> This version _will not_ correct the UUIDs - those are set to 0 on purpose. What it should do is let them display on the map -- that's the nature of this issue, not the UUID zeroing (intended, as HH2 does not store that data -- and there are issues with trying to interpolate that)

The warp1 that disappeared before does not appear on the dynmap

**Comment by WiIIiam278** [comment] 2022-09-15 15:47
Whoops, looks like there's a few more fixes to make.

**Comment by WiIIiam278** [comment] 2022-09-15 15:49
@ApliNi could you try this again with the new build f80261d on modrinth?

**Closed** 2022-09-15 15:48 UTC
Labels: type: bug

**Comment by WiIIiam278** [comment] 2022-10-11 08:27
Oh— real quick, is this the case with public homes? Or just warps?

**Comment by ApliNi** [comment] 2022-10-11 08:30
I haven't tested anything else. If necessary, I can try it after 20:00 today.

**Comment by ApliNi** [comment] 2022-10-11 13:26
phome will not be displayed on dynmap after the database is updated

**Comment by WiIIiam278** [comment] 2022-10-11 13:28
@ApliNi Hey -- I have no idea what's happened here, but this GitHub thread seems to be bugging out. I'm locking this for now.
