### ISSUE TITLE
this is a bug

### ISSUE THREAD

**Issue by DCE-114514** [WiIIiam278/HuskHomes2#419] opened 2023-05-29 11:48 UTC
hey bro
I'm sorry to bother you, but there's something wrong with him again ![27edef205d795f75.jpg](https://github.com/WiIIiam278/HuskHomes2/assets/132117183/013324cd-6507-4d86-a585-ccd6d1e9eced)

**Comment by WiIIiam278** [comment] 2023-05-29 12:02
Duplicate of https://github.com/WiIIiam278/HuskHomes2/issues/415.
Please don't open duplicate issues :)

**Closed by WiIIiam278** 2023-05-29 12:02 UTC
Labels: resolution: invalid

**Comment by DCE-114514** [comment] 2023-05-29 12:03
> Duplicate of https://github.com/WiIIiam278/HuskHomes2/issues/415.
> Please don't open duplicate issues :)

Dude, these two are different.

**Comment by WiIIiam278** [comment] 2023-05-29 12:05
The two are the same underlying issue, which requires further investigation. You must be patient.
