### ISSUE TITLE
Teleport cross-server is not working properly

### ISSUE THREAD

**Issue by notrazer40** [WiIIiam278/HuskHomes2#147] opened 2022-02-15 04:32 UTC
**Specs**
- Java 16 
- Paper 1.17.1
- Latest version of HuskHome
- SQL 
- Redis

**Issue:**
Teleport commands as /warp, /spawn, /home, /tpa, /back, etc are not teleporting to the destination but to the previous location. Only when its cross-server teleport. Its a random behaviour, does not happens always.
Example: I sethome in **server1-overworld** at coords 100 100 100, after that i walk to coords 500 100 500. Then, i do /spawn that will send me to the **spawn-server**. And finally, i execute /home and i will be teleported to **server1-overworld** but to coords 500 100 500 instead of teleporting me to my home-> coords 100 100 100.

**Expected behaviour**
To actually teleport where it suppose to.

**Comment by msmanui** [comment] 2022-02-15 04:34
I forgot to mention that i am using SQL + Redis.

**Comment by WiIIiam278** [comment] 2022-02-15 10:29
Duplicate of #143 but thanks for the detailed reporting, updated that issue with the body of this one.

**Closed** 2022-02-15 10:29 UTC
